### ISSUE TITLE
Themes should be global

### ISSUE THREAD

**Issue by JoyalAJohney** [Excel-MEC/Excel-App-2020#21]
Fonts, colors, and text styles of cards need to be global. Add it to themes.dart file

**Comment by steevjames** [comment]
Most colors and all fonts used are already taken from lib/UI/constants.dart. The app theme can be changed by changing values in it. However more values will be moved to it soon.

**Comment by JoyalAJohney** [comment]
Will specify a 'TODO: move to constants' wherever encountered. It'll be easy to keep track in the future.
